/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#0f6b78',
        'on-primary': '#ffffff',
        'primary-container': '#c3f1f6',
        'on-primary-container': '#073b43',
        secondary: '#2f7d5c',
        'on-secondary': '#ffffff',
        'secondary-container': '#c7f0d8',
        'on-secondary-container': '#0c3b26',
        tertiary: '#b65c28',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#ffdbc7',
        'on-tertiary-container': '#4b1b05',
        error: '#b3261e',
        'on-error': '#ffffff',
        'error-container': '#f9dedc',
        'on-error-container': '#601410',
        background: '#f4f8fa',
        'on-background': '#18262d',
        surface: '#f9fbfc',
        'on-surface': '#18262d',
        'surface-dim': '#dce6e9',
        'surface-bright': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eef4f6',
        'surface-container': '#e7eff2',
        'surface-container-high': '#dfe9ec',
        'surface-container-highest': '#d5e2e6',
        'surface-variant': '#dce8eb',
        'on-surface-variant': '#51636a',
        outline: '#71868d',
        'outline-variant': '#c5d3d7',
        'inverse-surface': '#29383e',
        'inverse-on-surface': '#edf6f8',
      },
      borderRadius: { DEFAULT: '0.375rem', lg: '0.625rem', xl: '0.875rem', full: '9999px' },
      fontFamily: { sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'] },
    },
  },
  plugins: [],
}

