import { useState } from 'react';

const pages = [
  { id: 'overview', label: 'Overview', icon: 'dashboard' },
  { id: 'chat', label: 'AI Assistant', icon: 'chat' },
  { id: 'calendar', label: 'Calendar', icon: 'calendar_month' },
  { id: 'doctors', label: 'Doctors', icon: 'medical_services' },
  { id: 'appointments', label: 'Appointments', icon: 'event_note' },
  { id: 'admin', label: 'Admin controls', icon: 'admin_panel_settings' },
];

function Status({ children, tone = 'success' }: { children: string; tone?: 'success' | 'warning' | 'info' }) {
  return <span className={`status-pill status-${tone}`}><span className="status-dot" />{children}</span>;
}

function Overview() {
  return <div className="preview-grid">
    <div className="preview-hero"><p className="eyebrow">Care operations preview</p><h2>A calm, coordinated view of patient care.</h2><p>Review this offline preview of the signed-in experience. Backend data is intentionally replaced with representative clinical records.</p><div className="preview-actions"><Status>System ready</Status><span className="muted-text">Demo data only</span></div></div>
    <div className="preview-stats"><div><span>Upcoming visits</span><strong>04</strong><small>Next 7 days</small></div><div><span>Care team</span><strong>08</strong><small>Available today</small></div><div><span>Open requests</span><strong>03</strong><small>Needs review</small></div></div>
    <div className="preview-card preview-wide"><div className="card-heading"><div><p className="eyebrow">Today&apos;s care plan</p><h3>Tuesday, October 6</h3></div><Status tone="info">4 scheduled</Status></div><div className="timeline-row"><span className="time">09:30</span><div><strong>Dr. Maya Patel</strong><p>Primary care follow-up · Room 204</p></div><Status>Confirmed</Status></div><div className="timeline-row"><span className="time">14:00</span><div><strong>Lab results review</strong><p>Care team video consultation</p></div><Status tone="warning">Check in</Status></div></div>
    <div className="preview-card"><p className="eyebrow">Care team message</p><h3>How can we help today?</h3><p className="muted-text">Ask the assistant about symptoms, appointments, or preparation instructions.</p><button className="preview-primary" type="button">Open AI assistant <span className="material-symbols-outlined">arrow_forward</span></button></div>
  </div>;
}

function Chat() { return <div className="preview-chat"><div className="preview-card chat-card"><div className="card-heading"><div className="avatar avatar-teal">AI</div><div><h3>Stellaris Care Assistant</h3><p className="muted-text">Secure patient guidance</p></div><Status>Online</Status></div><div className="chat-messages"><div className="chat-bubble assistant">Hello, Alex. I can help you find a doctor, prepare for an appointment, or understand your next steps.</div><div className="chat-bubble patient">I need to reschedule my cardiology visit.</div><div className="chat-bubble assistant">I found your upcoming visit with Dr. Omar Lewis on Thursday at 10:30 AM. Would you like to see available times?</div></div><div className="chat-composer"><span>Type a message...</span><button className="preview-primary icon-button" type="button"><span className="material-symbols-outlined">send</span></button></div></div><aside className="preview-card"><p className="eyebrow">Assistant can help with</p><ul className="preview-list"><li><span className="material-symbols-outlined">event_available</span>Appointments and check-in</li><li><span className="material-symbols-outlined">medication</span>Preparation and medications</li><li><span className="material-symbols-outlined">support_agent</span>Connecting with your care team</li></ul></aside></div>; }

function Calendar() { return <div className="preview-card"><div className="card-heading"><div><p className="eyebrow">Schedule</p><h2>October 2026</h2></div><div className="calendar-actions"><button type="button">‹</button><button type="button">Today</button><button type="button">›</button></div></div><div className="calendar-week">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(day => <span key={day}>{day}</span>)}</div><div className="calendar-days">{Array.from({ length: 35 }, (_, index) => <div key={index} className={`calendar-day ${index === 6 || index === 20 ? 'selected-day' : ''}`}><span>{index < 3 ? '' : ((index - 2) % 31) + 1}</span>{index === 6 && <b>Dr. Patel · 09:30</b>}{index === 20 && <b>Lab review · 14:00</b>}</div>)}</div></div>; }

function Doctors() { return <div className="preview-card"><div className="card-heading"><div><p className="eyebrow">Care directory</p><h2>Find your care team</h2></div><button className="preview-secondary" type="button"><span className="material-symbols-outlined">filter_list</span>Filter</button></div><div className="doctor-list">{[['MP','Maya Patel','Primary Care','Available today'],['OL','Omar Lewis','Cardiology','Next available Thu'],['SR','Sofia Reyes','Dermatology','Available tomorrow']].map(([initials,name,specialty,availability]) => <div className="doctor-row" key={name}><div className="avatar avatar-blue">{initials}</div><div><strong>{name}</strong><p>{specialty}</p></div><Status tone={availability.includes('today') ? 'success' : 'info'}>{availability}</Status><button className="preview-secondary" type="button">View profile</button></div>)}</div></div>; }

function Appointments() { return <div className="preview-card"><div className="card-heading"><div><p className="eyebrow">Patient appointments</p><h2>Upcoming visits</h2></div><button className="preview-primary" type="button">Book appointment</button></div><div className="appointment-row"><div className="date-block"><strong>06</strong><span>OCT</span></div><div><strong>Primary care follow-up</strong><p>Dr. Maya Patel · Tue, Oct 6 · 09:30 AM</p></div><Status>Confirmed</Status><button className="preview-secondary" type="button">Manage</button></div><div className="appointment-row"><div className="date-block"><strong>15</strong><span>OCT</span></div><div><strong>Cardiology consultation</strong><p>Dr. Omar Lewis · Thu, Oct 15 · 10:30 AM</p></div><Status tone="warning">Check in</Status><button className="preview-secondary" type="button">Manage</button></div></div>; }

function Admin() { return <div className="preview-card"><div className="card-heading"><div><p className="eyebrow">Operations console</p><h2>Assign care requests</h2></div><Status tone="warning">3 pending</Status></div><div className="admin-table"><div className="admin-head"><span>Patient request</span><span>Priority</span><span>Assigned team</span><span>Action</span></div>{[['A. Johnson','Routine follow-up','Primary Care'],['R. Williams','Chest discomfort','Cardiology'],['K. Smith','Medication review','Pharmacy']].map(([patient,request,team]) => <div className="admin-row" key={patient}><div><strong>{patient}</strong><p>{request}</p></div><Status tone={request.includes('Chest') ? 'warning' : 'info'}>{request.includes('Chest') ? 'Urgent' : 'Routine'}</Status><select defaultValue={team} aria-label={`Assign ${patient}`}><option>Primary Care</option><option>Cardiology</option><option>Pharmacy</option></select><button className="preview-primary" type="button">Assign</button></div>)}</div></div>; }

type PreviewPageId = 'overview' | 'chat' | 'calendar' | 'doctors' | 'appointments' | 'admin';

export default function Preview() { const [active, setActive] = useState<PreviewPageId>('overview'); const content = { overview: <Overview />, chat: <Chat />, calendar: <Calendar />, doctors: <Doctors />, appointments: <Appointments />, admin: <Admin /> }[active]; return <main className="preview-shell"><header className="preview-topbar"><div className="brand-lockup"><img src="/images/logo.png" alt="Stellaris General Hospital" /><div><strong>Stellaris</strong><span>General Hospital</span></div></div><div className="preview-label"><span className="material-symbols-outlined">visibility</span>Offline UI preview</div><a href="/login" className="preview-exit">Exit preview</a></header><div className="preview-layout"><nav className="preview-nav" aria-label="Preview pages"><p className="eyebrow">Signed-in workspace</p>{pages.map(page => <button type="button" key={page.id} className={active === page.id ? 'active' : ''} onClick={() => setActive(page.id as PreviewPageId)}><span className="material-symbols-outlined">{page.icon}</span>{page.label}</button>)}</nav><section className="preview-main"><div className="preview-breadcrumb">Workspace <span>/</span> {pages.find(page => page.id === active)?.label}</div>{content}</section></div></main>; }

